### ISSUE TITLE
pls support php7

### ISSUE THREAD

**Issue by dkeepersun** [nrk/phpiredis#43]
can't use at php7 now . pls support it.   thanks !  :+1:

**Comment by Enleur** [comment]
+1

**Comment by drefined** [comment]
There's currently a PR for this https://github.com/nrk/phpiredis/pull/39. I'm patiently waiting. :+1:

**Comment by dkeepersun** [comment]
+2

**Comment by quantverse** [comment]
:+1:  +1

**Comment by Orion1** [comment]
+1

**Comment by dkeepersun** [comment]
+3

**Comment by moechofe** [comment]
+1

**Comment by ellisthedev** [comment]
+1 would love to have this enabled on production again. :)

**Comment by mmucklo** [comment]
What happened to this package - is anyone maintaining it?  Should someone fork and should we all move on?

**Comment by nrk** [comment]
@mmucklo this library is not abandoned, but it's been months since the last time I had time for my opensource projects and I myself am quite unhappy about the situation. That said, #39 is a starting point for PHP7 compatibility but it's a bit messy so I'm not so keen about merging it as-is. Unfortunately +1s and similar stuff don't help, contributions do. Actual help to improve that PR would be more than appreciated and would speed things up. Thanks.

**Comment by rchunping** [comment]
+1 
please support php7
it's a good extension, we use this 3 years

**Comment by muratmoon** [comment]
+1
This is the only extension keeping us from PHP 7.

**Comment by Cysioland** [comment]
:+1:

**Comment by Barbery** [comment]
+1

**Comment by plessmann** [comment]
I also vote for this feature   :+1:

**Comment by nrk** [comment]
Closing this issue as we are almost there! See #50 for details.
