### ISSUE TITLE
Install ext-phpiredis On Mac El Capitan

### ISSUE THREAD

**Issue by pcruse3** [nrk/phpiredis#51]
Hi,

I have put this line in my composer file `"ext-phpiredis": "*"`. 

When I run `composer update` I get this error:  `- The requested PHP extension ext-phpiredis * is missing from your system. Install or enable PHP's phpiredis extension.`

I can't seem to find out to install your package on with homebrew or ubuntu `apt-get` anywhere.

I don't want to have to install and make the package myself.

Are you on any package manager.

**Comment by nrk** [comment]
Hi @pcruse3, this extension is not available on homebrew or ubuntu (or any package manager for that matter, maybe on linux distributions it's provided by some third party channel such as Ubuntu PPA or ArchLinux AUR). Part of the reason is that phpiredis does not have a proper and fixed release yet but I will officially push v1.0.0 this weekend after having observed that it seems to be working fine after the various changes needed to make it work with PHP >= 7.0.

Anyway I'm closing this issue since the specific request about Homebrew is already covered by #29. As for Linux distributions I'm still hoping for someone to contribute scripts and such needed to make it easy to build deb and rpm packages.
